In [151]:
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup

In [152]:
fd1 = pd.read_csv('burtgel_company.csv')
fd1 = pd.DataFrame(fd1)
fd1

,Аж ахуйн нэгжийн нэр,Регистерийн дугаар,Улсын бүртгэлийн дугаар,Үйл ажиллагааны чиглэл,Утас,Факсын дугаар,Хаяг
0,Тэнүүн-Огоо,5103258,11,8.472175e+10,NaN,NaN,NaN
1,ХУДАЛДАА ХӨГЖЛИЙН БАНК,2635534,9,5.826890e+10,NaN,NaN,NaN
2,БЗД НДХ,9095497,10,5.157261e+10,NaN,NaN,NaN
3,СХД-ИЙН НДХ,9091831,7,4.825204e+10,NaN,NaN,NaN
4,Монгол улсын хөгжлийн банк,5461626,2,4.600000e+10,NaN,NaN,NaN
...,...,...,...,...,...,...,...
5183,Мандал органик фүүдс хоршоо,3767817,1,5.000000e+06,NaN,NaN,NaN
5184,БАТ ӨЛЗИЙ СУМ ТОХИЖИЛТ ҮЙЛЧИЛГЭЭ ААТҮГ,3565793,1,5.000000e+06,NaN,NaN,NaN
5185,Шигү фильм,5535557,1,5.000000e+06,NaN,NaN,NaN
5186,Өнөөдөр нисэхт ТББ,6601405,1,5.000000e+06,NaN,NaN,NaN
5187,Өмнөговь аймгийн Боксын холбоо,8200882,1,5.000000e+06,NaN,NaN,NaN

In [153]:
fd1 = fd1.drop(columns=['Улсын бүртгэлийн дугаар', 'Үйл ажиллагааны чиглэл','Утас', 'Факсын дугаар', 'Хаяг'])
fd1.to_csv('data.csv', index=False)

In [154]:
fd1 = pd.read_csv('data.csv')
fd1 = pd.DataFrame(fd1)
fd1.shape

(5188, 2)

In [155]:
fd2 = pd.read_csv('company.csv')
fd2 = pd.DataFrame(fd2)
fd2.shape

(1798, 7)

In [156]:
data = pd.concat([fd2, fd1], ignore_index=True)
data.shape

(6986, 7)

In [157]:
duplicateRows = data[data.duplicated(['Аж ахуйн нэгжийн нэр'])]

In [158]:
duplicateRows

,Аж ахуйн нэгжийн нэр,Регистерийн дугаар,Улсын бүртгэлийн дугаар,Үйл ажиллагааны чиглэл,Утас,Факсын дугаар,Хаяг
289,Дэд өртөө ХХК,2568756,9011171129,"0,4-35 кВ-ын ЦДШ, дэд станцын угсралт.Барилгын...",686327,NaN,"БГД, 15-р хороо, Техник импорт ХК-н байр, 310 ..."
416,Дрийм Оазис ХХК,5497337,9011260057,"Гадаад худалдаа, засал чимэглэл","3424788, 91007960",NaN,"СБД 5-р хороо, 5-р хороолол JS Tower-701"
494,Гандирс Орд ХХК,2027232,9011179031,NaN,NaN,NaN,NaN
608,Карст,50008999,9011025027,Усны эрэл хайгуул өрөмдлөг хийх,99889945,99889945,"УБ, БГД, 5-р хороо, 10-р хороолол 11-54"
719,Хөххайрхан трейд”,2708507,9011021090,"Барилга угсралт, барилга засвар",NaN,632744,"Улаанбаатар хот, Сонгинохайрхан дүүрэг, 19 хор..."
...,...,...,...,...,...,...,...
6981,Мандал органик фүүдс хоршоо,3767817,NaN,NaN,NaN,NaN,NaN
6982,БАТ ӨЛЗИЙ СУМ ТОХИЖИЛТ ҮЙЛЧИЛГЭЭ ААТҮГ,3565793,NaN,NaN,NaN,NaN,NaN
6983,Шигү фильм,5535557,NaN,NaN,NaN,NaN,NaN
6984,Өнөөдөр нисэхт ТББ,6601405,NaN,NaN,NaN,NaN,NaN
6985,Өмнөговь аймгийн Боксын холбоо,8200882,NaN,NaN,NaN,NaN,NaN

In [159]:
company = data.drop_duplicates(['Аж ахуйн нэгжийн нэр'], keep='first')
company

,Аж ахуйн нэгжийн нэр,Регистерийн дугаар,Улсын бүртгэлийн дугаар,Үйл ажиллагааны чиглэл,Утас,Факсын дугаар,Хаяг
0,Наран тээл ХХК,2832097,9011084095,"Барилгын засвар, засал чимэглэл, угсралт",681096,681096,NaN
1,БЦХ,2768224,9011112070,"Барилгын засал чимэглэл, угсралт",350310,350310,"СБД, 7-р хороо, 11-р хороолол 5-43"
2,Бүтээлч шинэ сонголт ХХК,5033772,9011009068,"Барилгын засвар, засал чимэглэл, угсралт",367387,367387,"СБД, 7-р хороо, 3-р хороолол,2-А-69 тоот"
3,Миний Сайн шанд ХХК,2771233,611008276,"Барилгын засвар, засал чимэглэл, угсралт",1,1,"Дорноговь, Сайншанд,2-р баг"
4,Бодиз Автомотив ХХК,2108364,9011063140,"Автомашин болон машины сэлбэгийн худалдаа, Гад...",318482,327812,"Улаанбаатар 14230, Сүхбаатар дүүрэг, Нарны зам..."
...,...,...,...,...,...,...,...
6887,Хашзандан,2059002,NaN,NaN,NaN,NaN,NaN
6888,БАЯНСОГООТ ТРЕЙД,5775477,NaN,NaN,NaN,NaN,NaN
6889,Радианс энд майнд,5548551,NaN,NaN,NaN,NaN,NaN
6890,Тэгштүмэн зоос,5345618,NaN,NaN,NaN,NaN,NaN
6891,ЗАВХАН АЙМГИЙН ДАЯН МЭРГЭН ХАРВААЧДЫН ХОЛБОО,8063516,NaN,NaN,NaN,NaN,NaN

In [160]:
company = company.drop_duplicates(['Регистерийн дугаар'], keep='first')

In [161]:
duplicateRows = company[data.duplicated(['Регистерийн дугаар'])]
duplicateRows

/tmp/ipykernel_2684/3127061182.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  duplicateRows = company[data.duplicated(['Регистерийн дугаар'])]

Empty DataFrame
Columns: [Аж ахуйн нэгжийн нэр, Регистерийн дугаар, Улсын бүртгэлийн дугаар, Үйл ажиллагааны чиглэл, Утас, Факсын дугаар, Хаяг]
Index: []

In [164]:
company.to_csv('data_company.csv', index=False)

In [165]:
company.shape

(6566, 7)